version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - ".docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - .docker/volumes/pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    image: vuhn07/go-app-sample
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_NAME=go-app-sample
      - DB_SSL_MODE=disable
