version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/go:1.18.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: cd src; go get ./...
      - run:
          name: Run tests
          command: make unittest
  deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/app
    steps:
      - checkout
      - run: echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/service-account-key.json
      - run: 
          name: Deploy to GCP
          command: make ci-deploy-gcp KEYFILE=${HOME}/service-account-key.json

workflows:
  version: 2.1
  build:
    jobs:
      - build
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
