// Code generated by mockery v2.10.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entity "github.com/vuhn/go-app-sample/entity"
)

// TaskService is an autogenerated mock type for the TaskService type
type TaskService struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: _a0
func (_m *TaskService) CreateTask(_a0 *entity.Task) (*entity.Task, error) {
	ret := _m.Called(_a0)

	var r0 *entity.Task
	if rf, ok := ret.Get(0).(func(*entity.Task) *entity.Task); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Task) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
