// Code generated by mockery v2.10.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	entity "github.com/vuhn/go-app-sample/entity"
)

// TaskRepository is an autogenerated mock type for the TaskRepository type
type TaskRepository struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: task
func (_m *TaskRepository) CreateTask(task *entity.Task) (*entity.Task, error) {
	ret := _m.Called(task)

	var r0 *entity.Task
	if rf, ok := ret.Get(0).(func(*entity.Task) *entity.Task); ok {
		r0 = rf(task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Task) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
